config/routes.rb
Rails.application.routes.draw do

  get 'account/edit'
  patch 'account/update'
  get 'account/usercompany'

  ActiveAdmin.routes(self)
  resources :companies, :customers, :orders
  root 'welcome#index'

  resources :orders
  get 'welcome/index'

  resources :customers
  get 'welcome/index'

  resources :companies
  get 'welcome/index'
  get 'account/usercompany'

end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :customers
  belongs_to :user
  mount_uploader :image, PictureUploader
end

app/models/customer.rb
class Customer < ActiveRecord::Base
belongs_to :company
has_many :orders
end

app/models/order.rb
class Order < ActiveRecord::Base
belongs_to :customer
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :companies
  mount_uploader :avatar, PictureUploader
end

app/controllers/account_controller.rb
class AccountController < ApplicationController

  def update
    if current_user.update(user_params)
      redirect_to account_edit_path, notice: 'Your account is now updated.'
    else
      render :edit
    end
  end

  def edit
  end

  def show
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:name, :email, :avatar)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :current_user

  def authenticate_admin_user!
    redirect_to root_path if !signed_in? || !current_user.admin?
  end

  helper_method :signed_in?, :current_user

  def current_user
    @current_user ||= User.find_by(email: "guest@guest.com")
  end

  def signed_in?
    return true if current_user
  end

end

app/controllers/companies_controller.rb
class CompaniesController < InheritedResources::Base

  def index
    @usercompany = current_user.companies
    logger.debug "DEBUG THIS LINE"
    logger.debug @companies.inspect
  end

  private

  def company_params
    params.require(:company).permit(:name, :bio, :image)
  end
end

app/controllers/customers_controller.rb
class CustomersController < InheritedResources::Base
  def index
    @customers = Customer.all
  end

  private

  def customer_params
    params.require(:customer).permit(:name, :order, :company_id)
  end
end

app/controllers/orders_controller.rb
class OrdersController < InheritedResources::Base

  private

    def order_params
      params.require(:order).permit(:number, :quantity, :item)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company, :html => {:multipart => true} ) do |f| %>
<% if @company.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

  <ul>
    <% @company.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div>
  <br>

  <%= f.file_field :image %><br><br>

</div>
<div class="field">
  <%= f.label :id %><br><br>
  <%= f.text_field :id %>
</div>

<div class="field">
  <%= f.label :name %><br><br>
  <%= f.text_field :name %>
</div>


<div class="field">
  <%= f.label :bio %><br>
  <%= f.text_area :bio %>
</div>


<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>



<%= render 'form' %>

<%= link_to 'Show Company', @company %> |
<%= link_to 'Back to previous', companies_path %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class = tbody>Listing All Companies</h1>

<table>
  <thead>
    <tr>
      <th>Company<br>ID</th>
      <th>Customer<br>count</th>
      <th>Company<br>logo</th>
      <th>Company<br>name</th>

      <th>Company<br>Bio</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @usercompany.each do |company| %>
      <tr>
        <td><%= company.id %></td>
        <td><%= image_tag company.image_url(:thumb) if company.image? %></td>
        <td><%= company.name %></td>
        <td><%= company.customers.count %></td>
        <td><%= company.bio %></td>
        <td><nav><%= link_to 'Show Record', company %></nav></td>
        <td><nav><%= link_to 'Edit Record', edit_company_path(company) %></nav></td>
        <td><nav><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></nav></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<nav><%= link_to 'New Company', new_company_path %>
<%= link_to 'Return to Main Page', root_path %></nav><br>
<a href="http://www.theironyard.com">Visit The Iron Yard!</a>

app/views/companies/new.html.erb
<h1>New Company</h1>


<%= render 'form' %>

<%= link_to 'Back', companies_path %>
<%= link_to 'Return to Main Page', root_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @company.image_url.to_s %>

<p>
  <strong>Company name:</strong>
  <%= @company.name %>
</p>


<p>
  <strong>Company bio:</strong>
  <%= @company.bio %>
</p>



<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>
<%= link_to 'Return', root_path %>

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
<% if @customer.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

  <ul>
    <% @customer.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :name %><br>
  <%= f.text_field :name %>
</div>
<div class="field">
  <%= f.label :order %><br>
  <%= f.number_field :order %>
</div>


<div class="field">
  <%= f.label Company %><br>
  <%= f.select :company_id, Company.all.collect {|p| [ p.name, p.id ] }, {include_blank: 'None'}, {class: 'chosen-select'} %>

</div>

<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Customers</h1>

<table>
  <thead>
    <tr>
      <th>Customer<br>name</th>
      <th>Customer<br>order</th>
      <th>Company<br>ID</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.name %></td>
        <td><%= customer.order %></td>
        <td><%= customer.company_id %></td>

        <td><%= link_to 'Show Customer', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>
<%= link_to 'Return to Main Page', root_path %>

app/views/customers/new.html.erb
<h1>Enter A New Customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>
<%= link_to 'Return to Main Page', root_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer name:</strong>
  <%= @customer.name %>
</p>

<p>
  <strong>Customer order:</strong>
  <%= @customer.order %>
</p>

<p>
  <strong> Company :</strong>
  <%= @customer.company_id %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> <br>
<%= link_to 'Back', customers_path %><br>
<%= link_to 'Return to Main Page', root_path %><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">

  <div>
    <h1><title>Company Application</title></h1>
  </div>

</head>


<div>
  <body>
    <h3>Welcome To The Application User: <% if signed_in? %><%= link_to @current_user.name, account_edit_path %><% end %></h3>
  </body>
</div>

<%= yield %>

</html>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>

  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>

  <div class="field">
    <%= f.label :item %><br>
    <%= f.text_field :item %>
  </div>

    <div class="field">
      <%= f.label :customer_id %><br>
      <%= f.text_field :customer_id %>
    </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Orders</h1>

<table>
  <thead>
    <tr>
      <th>Order<br>number</th>
      <th>Order<br>quantity</th>
      <th>Order<br>item</th>
      <th>Customer<br>ID</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.number %></td>
        <td><%= order.quantity %></td>
        <td><%= order.item %></td>
        <td><%= order.customer_id %></td>

        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>
<%= link_to 'Return to Main Page', root_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>
<%= link_to 'Return to Main Page', root_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Order number:</strong>
  <%= @order.number %>
</p>

<p>
  <strong>Order quantity:</strong>
  <%= @order.quantity %>
</p>

<p>
  <strong>Order item:</strong>
  <%= @order.item %>
</p>


<h4>
<%= link_to 'Edit', edit_order_path(@order) %> <br>
<%= link_to 'Back', orders_path %><br>
<%= link_to 'Return to Main Page', root_path %></h4>

app/views/welcome/index.html.erb
<html>
<head>
  <h1>Welcome to the Company Project Site</h1>

</head>
<body>

</body>
<div><br>
  <a class="btn btn-default" href="Companies" role="button">Link to Companys</a>

  <a class="btn btn-default" href="Customers" role="button">Link to Customers</a>

  <a class="btn btn-default" href="Orders" role="button">Link to Orders</a>

</div>

</html>